export const SWITCH_THREAD = 'SWITCH_THREAD'
export const RECEIVE_ALL = 'RECEIVE_ALL'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const GET_USER_INFO = 'get_user_info'
export const GET_USER_TOKEN = 'get_user_token'
export const SET_USER_LIST = 'set_user_list'
export const GET_CURRENT_USER = 'get_current_user'
export const CHANGE_CURRENT_THREAD_INFO = 'change_current_thread_info' // 改变当前用户
export const SEND_MESSAGE = 'send_message'
export const INIT_WINDOW = 'init_window'
export const GET_HISTORY_MESSAGE = 'get_history_message'
export const SET_SEARCH_NAME = 'set_search_name' // 侧边栏搜索实时刷新用
export const UPDATE_USERLIST_INFO = 'update_userlist_info'
